apiVersion: v1
kind: Service
metadata:
  name: simple-argo-docker-app-service
spec:
  selector:
    app: simple-argo-docker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
